#!/usr/bin/env bash
# Install nginx on a remote server.
# Write a Bash script that configures a new Ubuntu machine
sudo apt-get -y update && upgrade
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
service nginx start
