#!/usr/bin/env bash
# Install nginx on a remote server and configures a new Ubuntu machine
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo touch /var/www/html/index.html
sudo echo "Hello World!" > /var/www/html/index.html
sudo service nginx start
