#!/usr/bin/env bash
# Write 4-not_found_page_404 so that it configures a brand new Ubuntu machine

sudo apt-get update
sudo apt-get install -y nginx

# Code to redirect to specific endpoint
echo "Hello World!" | sudo tee /var/www/html/index.html
replacement_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.google.com permanent;"

sudo sed -i "s/server_name _;/$replacement_string/" /etc/nginx/sites-enabled/default

# Create error page and add redirect for error 404
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
replacement_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$replacement_string/" /etc/nginx/sites-enabled/default

# restart server
sudo service nginx restart

