#!/usr/bin/env bash
# Install & configure HAproxy so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm
sudo apt-get -y update
apt-get -y install haproxy

# edit the config file
server_config=\
"
frontend  amypetua-frontend
	bind *:80
	mode http
	default_backend amypetua-backend
backend amypetua-backend
	balance roundrobin
	server 203610-web-01 107.22.142.244:80 check
	server 203610-web-02 54.162.82.254:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

 # enable haproxy

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
