#!/usr/bin/env bash
# Script that creates a file, displays a processand deletes the file

terminator()
{
	rm /var/run/myscript.pid
	exit
}

PID=$$

echo $PID > /var/run/myscript.pid

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I hate the kill command"' SIGTERM
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'terminator' SIGQUIT
done
