#!/usr/bin/env bash
# Script that displays the content of the file /etc/passwd

while read -r line;
do
	username=$(echo "$line" | cut -d: -f1)
	user_id=$(echo "$line" | cut -d: -f3)
	home_dir=$(echo "$line" | cut -d: -f6)

	echo "Username: $username"
	echo "User ID: $user_id"
	echo "Home Directory path of the user: $home_dir"
done < /etc/passwd
