#!/usr/bin/env bash
# Script that displays Best School 10 times but 9th iteration displays Hi

num=1
while [ $num -le 10 ]
do
	if [ $num -eq 9 ]
	then
		echo "Hi"
	else
		echo "Best School"
	fi

	num=$((num+1))
done
