#!/usr/bin/env bash
# Script that display Best School 10 times & bad luck at 4th, good luck at 8th

num=1
while [ $num -le 10 ]
do
	if [ $num -eq 4 ]
	then
		echo "bad luck"
	elif [ $num -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi

	num=$((num+1))
done
