#!/usr/bin/env bash
# Scripts that displays 1 to 20 and words inbetween specific numbers

num=1
while [ $num -le 20 ]
do
	echo $num

	if [ $num -eq 4 ]
	then
			echo "bad luck from China"
	elif [ $num -eq 9 ]
	then
		echo "bad luck from Japan"
	elif [ $num -eq 17 ]
	then
		echo "bad luck from Italy"
	fi

	num=$((num+1))
done
