#!/usr/bin/env bash
# Script that displays the content of a current directory in a list format

for file in *
do
	if [[ -f $file ]];
	then
		name=$(echo "$file" | cut -d'-' -f2-)
		echo "$name"
	fi
done
