#!/usr/bin/env bash
# Script that gibes information about the school file

file_path="root@167c89d1969b/alx-system_engineering-devops/0x04-loops_conditions_and_parsing/school"

if [ -e "$file_path" ]
then
	echo "school file exists"

	if [ -s "$file_path" ]
	then
		echo "school file is empty"
	else
		echo "school file is not empty"
	fi

	if [ -f "$file_path" ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
