#!/usr/bin/env bash

# Script that configures an Ubuntu server in the following way:
# -localhost resolves to 127.0.0.2
# -facebook.com resolves 8.8.8.8

echo -e "127.0.0.2\tlocalhost" | sudo tee -a /etc/hosts
echo -e "8.8.8.8\tfacebook.com" | sudo tee -a /etc/hosts
