#!/usr/bin/env bash

# Script that configures an Ubuntu server in the following way:
# -localhost resolves to 127.0.0.2
# -facebook.com resolves 8.8.8.8

echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts

sudo service networking restart
